spring:
  application:
    name: booking-system
  datasource:
    initialization-mode : always
    url: jdbc:postgresql://localhost:5432/booking # PostgreSQL JDBC URL
    username: postgres              # Your PostgreSQL username
    password: kkl@14994              # Your PostgreSQL password
    driver-class-name: org.postgresql.Driver        # PostgreSQL Driver class
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  #      schema-locations: classpath:schema.sql

  main:
    allow-circular-references: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
