spring:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always
  #      schema-locations: classpath:schema.sql

  main:
    allow-circular-references: true

  application:
    name: BOOKING-SYSTEM-V2

  profiles:
    active: dev

server:
  port: 8080